services:
  # can change the permission of the folder
  db:
    image: postgres:16.3-alpine3.18
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    shm_size: 250mb

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_DB: database

    deploy:
      resources:
        limits:
          memory: 300M

  webhook: &deno
    image: denoland/deno:alpine
    labels:
      function: "true"
    environment:
      NODE_ENV: "production"
    shm_size: 25mb
    restart: always
    memswap_limit: 50M

    volumes:
      - ./services/webhook:/app
    ports:
      - 501:3000
    expose:
      - "3000"

    command: run --allow-net /app/main.ts

    deploy:
      resources:
        limits:
          memory: 25M
          cpus: "1.0"

  math:
    <<: *deno
    volumes:
      - ./services/math:/app
    ports:
      - 502:3000
