[package]
name = "servitor"
version = "0.1.0"
edition = "2021"

[dependencies]
quickjs_runtime = { version = "0.11" }
anyhow = "1.0.76"
log = "0.4.20"
simple-logging = "2.0.2"
serde_json = "1.0"
serde = "1.0"
